\input texinfo   @c -*-texinfo-*-

@set title Lab 2: Processor Exceptions
@set subtitle Computer Architecture
@set splash1 lab_2_processor_exceptions-splash.texi
@set splash2 westminster-splash.texi
@set author Scott Overholser
@set category Laboratory
@set filename lab_2_processor_exceptions

@comment %**start of header
@setchapternewpage off
@setfilename @value{filename}.info
@settitle @value{title}
@finalout
@comment %**end of header

@include @value{filename}.texi.updated
@include copying.texi

@titlepage
@title @value{title}
@subtitle @value{subtitle}
@include @value{splash1}
@author @value{author}

@c Secondary title page.
@page
@include @value{splash2}
@vskip 0pt plus 1filll
@insertcopying
@end titlepage

@comment Table of Contents
@contents

@dircategory @value{category}
@direntry
* Texinfo Doc Template         Template for Creating New Docs
@end direntry

@include headings.texi
@include constants.texi

@ifnottex
@node Top
@top @value{title}

@insertcopying
@end ifnottex

@comment This is the Chapter Menu
@menu
* Lab Objective::           Lab Objective
* Notes::                   Notes
* Experiments::             Experiments
* Lab Report::              Lab Report
@end menu

@node Lab Objective
@chapter Lab Objective
@noindent
In this lab we will learn what processor exceptions are and how to handle them.

@node Notes
@chapter Notes
@noindent

@node Experiments
@chapter Experiments
@noindent

@node Lab Report
@chapter Lab Report
@noindent

@bye
