\input texinfo   @c -*-texinfo-*-

@set title Lab 1: Hello World
@set subtitle Computer Architecture
@set splash1 lab_1_hello_world-splash.texi
@set splash2 westminster-splash.texi
@set author Scott Overholser
@set category Laboratory
@set filename lab_1_hello_world

@comment %**start of header
@setfilename @value{filename}.info
@settitle @value{title}
@finalout
@comment %**end of header

@include @value{filename}.texi.updated
@include copying.texi

@titlepage
@title @value{title}
@subtitle @value{subtitle}
@include @value{splash1}
@author @value{author}

@c Secondary title page.
@page
@include @value{splash2}
@vskip 0pt plus 1filll
@insertcopying
@end titlepage

@comment Table of Contents
@contents

@dircategory @value{category}
@direntry
* Texinfo Doc Template         Template for Creating New Docs
@end direntry

@include headings.texi
@include constants.texi

@ifnottex
@node Top
@top @value{title}

@insertcopying
@end ifnottex

@comment This is the Chapter Menu
@menu
* Template Chapter::          TEMPLATE
@end menu

@comment This is a starting point.
@node Template Chapter
@chapter Customize This and Add More of Your Own
@cindex template, chapter
@noindent
Put your document here.

@bye
